import type { CSSProperties } from 'react';
import type { PhotoEditOperation } from '../../../boundary/contracts/core.ts';

function numericValue(operation: PhotoEditOperation, key: string, fallback: number): number { const candidate = operation.values[key]; return typeof candidate === 'number' && Number.isFinite(candidate) ? candidate : fallback; }
function fixed(value: number): string { return value.toFixed(3); }

export function adjustBrowserPreview(current: PhotoEditOperation, baseline: PhotoEditOperation): CSSProperties { const brightness = 1 + (numericValue(current, 'brightness', 0) - numericValue(baseline, 'brightness', 0)) / 200; const contrast = 1 + (numericValue(current, 'contrast', 0) - numericValue(baseline, 'contrast', 0)) / 100; const saturation = 1 + (numericValue(current, 'saturation', 0) - numericValue(baseline, 'saturation', 0)) / 100; return { filter: `brightness(${fixed(brightness)}) contrast(${fixed(contrast)}) saturate(${fixed(saturation)}) hue-rotate(${fixed(numericValue(current, 'hue', 0) - numericValue(baseline, 'hue', 0))}deg)` }; }
export function blurBrowserPreview(current: PhotoEditOperation, baseline: PhotoEditOperation): CSSProperties { const delta = numericValue(current, 'sigma', 2) - numericValue(baseline, 'sigma', 2); return delta >= 0 ? { filter: `blur(${fixed(delta * 0.75)}px)` } : { filter: `contrast(${fixed(1 - delta * 0.02)})` }; }
export function dehazeBrowserPreview(current: PhotoEditOperation, baseline: PhotoEditOperation): CSSProperties { const delta = numericValue(current, 'strength', 0.45) - numericValue(baseline, 'strength', 0.45); return { filter: `contrast(${fixed(1 + delta * 0.7)}) saturate(${fixed(1 + delta * 0.35)}) brightness(${fixed(1 - delta * 0.1)})` }; }
export function restoreBrowserPreview(current: PhotoEditOperation, baseline: PhotoEditOperation): CSSProperties { return { filter: `brightness(${fixed(numericValue(current, 'fadeRecovery', 1.08) / numericValue(baseline, 'fadeRecovery', 1.08))}) contrast(${fixed(1 + numericValue(current, 'contrast', 0.12) - numericValue(baseline, 'contrast', 0.12))}) saturate(${fixed(numericValue(current, 'saturation', 1.08) / numericValue(baseline, 'saturation', 1.08))})` }; }
export function rotateBrowserPreview(current: PhotoEditOperation, baseline: PhotoEditOperation): CSSProperties { return { transform: `rotate(${fixed(numericValue(current, 'angle', 0) - numericValue(baseline, 'angle', 0))}deg)` }; }
export function sharpenBrowserPreview(current: PhotoEditOperation, baseline: PhotoEditOperation): CSSProperties { const delta = numericValue(current, 'sigma', 1) - numericValue(baseline, 'sigma', 1); return { filter: `contrast(${fixed(1 + delta * 0.04)}) saturate(${fixed(1 + delta * 0.015)})` }; }
