// This file is generated by tooling/scripts/repo/generate-workflow-module-registry.mjs. Do not edit.
import type { WorkflowModulePlugin } from './contracts';
import plugin0 from './modules/plugins/detect-frames/manifest';
import plugin1 from './modules/plugins/scan-folder/manifest';

export const generatedWorkflowModulePlugins: readonly WorkflowModulePlugin[] = [
    plugin0,
    plugin1,
];
