// This file is generated by tooling/scripts/repo/generate-photo-edit-tool-registry.mjs. Do not edit.
import type { PhotoEditToolSuggestionPlugin } from './photoEditToolSuggestionRegistry.ts';
import plugin0 from '../../../services/photoEditing/tools/plugins/crop/automatic.ts';
import plugin1 from '../../../services/photoEditing/tools/plugins/focus/automatic.ts';
import plugin2 from '../../../services/photoEditing/tools/plugins/rotate/automatic.ts';

export const generatedPhotoEditToolSuggestionPlugins: readonly PhotoEditToolSuggestionPlugin[] = [
    plugin0,
    plugin1,
    plugin2,
];
