// This file is generated by tooling/scripts/repo/generate-photo-edit-tool-registry.mjs. Do not edit.
import type { PhotoEditToolUiPlugin } from './photoEditToolUiRegistry.ts';
import plugin0 from '../../../services/photoEditing/tools/plugins/adjust/ui.tsx';
import plugin1 from '../../../services/photoEditing/tools/plugins/colour-pop/ui.tsx';
import plugin2 from '../../../services/photoEditing/tools/plugins/crop/ui.tsx';
import plugin3 from '../../../services/photoEditing/tools/plugins/effects/ui.tsx';
import plugin4 from '../../../services/photoEditing/tools/plugins/focus/ui.tsx';
import plugin5 from '../../../services/photoEditing/tools/plugins/overlay/ui.tsx';
import plugin6 from '../../../services/photoEditing/tools/plugins/red-eye/ui.tsx';
import plugin7 from '../../../services/photoEditing/tools/plugins/rotate/ui.tsx';

export const generatedPhotoEditToolUiPlugins: readonly PhotoEditToolUiPlugin[] = [
    plugin0,
    plugin1,
    plugin2,
    plugin3,
    plugin4,
    plugin5,
    plugin6,
    plugin7,
];
