// This file is generated by tooling/scripts/repo/generate-photo-edit-tool-registry.mjs. Do not edit.
import type { PhotoEditToolBrowserPreviewPlugin } from '../../../services/photoEditing/photoEditToolPlugin.ts';
import plugin0 from '../../../services/photoEditing/tools/plugins/adjust/browserPreview.ts';
import plugin1 from '../../../services/photoEditing/tools/plugins/blur/browserPreview.ts';
import plugin2 from '../../../services/photoEditing/tools/plugins/dehaze/browserPreview.ts';
import plugin3 from '../../../services/photoEditing/tools/plugins/restore/browserPreview.ts';
import plugin4 from '../../../services/photoEditing/tools/plugins/rotate/browserPreview.ts';
import plugin5 from '../../../services/photoEditing/tools/plugins/sharpen/browserPreview.ts';

export const generatedPhotoEditToolBrowserPreviewPlugins: readonly PhotoEditToolBrowserPreviewPlugin[] = [
    plugin0,
    plugin1,
    plugin2,
    plugin3,
    plugin4,
    plugin5,
];
