import type { ReactNode } from 'react';
import type { PhotoEditOperation } from '@contracts/core';
import { PhotoColourPopOverlay } from './PhotoColourPopOverlay'; import { PhotoCropOverlay } from './PhotoCropOverlay'; import { PhotoEffectsOverlay } from './PhotoEffectsOverlay'; import { PhotoFocusOverlay } from './PhotoFocusOverlay'; import { PhotoRedEyeOverlay } from './PhotoRedEyeOverlay'; import { PhotoRotateOverlay } from './PhotoRotateOverlay'; import { PhotoTuneOverlay } from './PhotoTuneOverlay';
import { PhotoColourPopOptions } from './PhotoColourPopOptions'; import { PhotoCropOptions } from './PhotoCropOptions'; import { PhotoEffectsOptions } from './PhotoEffectsOptions'; import { PhotoFocusOptions } from './PhotoFocusOptions'; import { PhotoRedEyeOptions } from './PhotoRedEyeOptions'; import { PhotoRotateOptions } from './PhotoRotateOptions'; import { PhotoTuneOptions } from './PhotoTuneOptions'; import type { Asset } from '@contracts/core';
type Props = { operation: PhotoEditOperation; previewUrl: string | null; sourceUrl: string | null; showWithoutChange: boolean; previewRevision: number; onCommit: (operation: PhotoEditOperation) => void; onDraft: (operation: PhotoEditOperation) => void };
type Renderer = (props: Props) => ReactNode;
const overlays: Record<string, Renderer> = {
  adjust: (p) => !p.operation.maskId && <PhotoTuneOverlay operation={p.operation} previewUrl={p.previewUrl} showWithoutChange={p.showWithoutChange} sourceUrl={p.sourceUrl} />,
  crop: (p) => <PhotoCropOverlay operation={p.operation} previewRevision={p.previewRevision} previewUrl={p.previewUrl} showWithoutChange={p.showWithoutChange} sourceUrl={p.sourceUrl} onCommit={p.onCommit} onDraftChange={p.onDraft} />,
  rotate: (p) => <PhotoRotateOverlay operation={p.operation} showWithoutChange={p.showWithoutChange} sourceUrl={p.sourceUrl} onCommit={p.onCommit} onDraftChange={p.onDraft} />,
  colour_pop: (p) => <PhotoColourPopOverlay operation={p.operation} previewUrl={p.previewUrl} showWithoutChange={p.showWithoutChange} sourceUrl={p.sourceUrl} onChange={p.onCommit} />,
  effects: (p) => <PhotoEffectsOverlay operation={p.operation} previewUrl={p.previewUrl} showWithoutChange={p.showWithoutChange} sourceUrl={p.sourceUrl} onChange={p.onCommit} />,
  focus: (p) => <PhotoFocusOverlay operation={p.operation} previewUrl={p.previewUrl} showWithoutChange={p.showWithoutChange} sourceUrl={p.sourceUrl} onCommit={p.onCommit} onPreviewChange={p.onDraft} />,
  red_eye: (p) => <PhotoRedEyeOverlay operation={p.operation} previewUrl={p.previewUrl} showWithoutChange={p.showWithoutChange} onChange={p.onCommit} />,
};
export function renderPhotoEditToolOverlay(props: Props): ReactNode { return overlays[props.operation.tool]?.(props) ?? null; }
type ControlProps = { asset: Asset; operation: PhotoEditOperation; sourceUrl: string | null; onCommit: (operation: PhotoEditOperation) => void; onPreviewChange: (operation: PhotoEditOperation) => void };
const controls: Record<string, (props: ControlProps) => ReactNode> = { adjust: (p) => <PhotoTuneOptions operation={p.operation} onCommit={p.onCommit} onPreviewChange={p.onPreviewChange} />, crop: (p) => <PhotoCropOptions operation={p.operation} onChange={(operation) => { p.onPreviewChange(operation); p.onCommit(operation); }} />, rotate: (p) => <PhotoRotateOptions operation={p.operation} onCommit={p.onCommit} onPreviewChange={p.onPreviewChange} />, colour_pop: (p) => <PhotoColourPopOptions operation={p.operation} sourceUrl={p.sourceUrl} onCommit={p.onCommit} onPreviewChange={p.onPreviewChange} />, effects: (p) => <PhotoEffectsOptions operation={p.operation} onCommit={p.onCommit} onPreviewChange={p.onPreviewChange} />, focus: (p) => <PhotoFocusOptions operation={p.operation} onCommit={p.onCommit} onPreviewChange={p.onPreviewChange} />, red_eye: (p) => <PhotoRedEyeOptions asset={p.asset} operation={p.operation} sourceUrl={p.sourceUrl} onCommit={p.onCommit} onPreviewChange={p.onPreviewChange} /> };
export function renderPhotoEditToolControls(props: ControlProps): ReactNode { return controls[props.operation.tool]?.(props) ?? null; }
