import { RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { CSSProperties } from "react";
import type { PhotoEditOperation } from "@contracts/core";
import { Button, IconButton } from "../Primitives";
import { TUNE_CONTROL_RANGES, TUNE_IMAGE_CONTROLS, TUNE_IMAGE_DEFAULTS, TUNE_GUIDED_CONTROLS, formatTuneValue, isOutsideGuidedRange, tuneValue } from "./tuneImageControls";
import type { GuidedTuneImageControl, TuneImageControl, TunePresentation } from "./tuneImageControls";
import "./PhotoTuneOptions.css";

type Props = { readonly operation: PhotoEditOperation; readonly onCommit: (operation: PhotoEditOperation) => void; readonly onPreviewChange: (operation: PhotoEditOperation) => void; };
type Control = { key: TuneImageControl; label: string; help: string; track: string; };
type RangeStyle = CSSProperties & { "--tune-position": string; };
const CONTROLS: Record<TuneImageControl, Control> = {
  brightness: { key: "brightness", label: "Brightness", help: "Changes the overall light level.", track: "brightness" }, contrast: { key: "contrast", label: "Contrast", help: "Changes separation between darker and brighter values.", track: "contrast" },
  shadows: { key: "shadows", label: "Shadows", help: "Changes darker areas that still contain detail.", track: "shadows" }, midtones: { key: "midtones", label: "Midtones", help: "Changes the middle-brightness range.", track: "midtones" }, highlights: { key: "highlights", label: "Highlights", help: "Changes brighter areas that still contain detail.", track: "highlights" },
  blackPoint: { key: "blackPoint", label: "Black point", help: "Sets where dark detail becomes black.", track: "black-point" }, whitePoint: { key: "whitePoint", label: "White point", help: "Sets where bright detail becomes white.", track: "white-point" },
  temperature: { key: "temperature", label: "Temperature", help: "Corrects a cool or warm colour cast.", track: "temperature" }, tint: { key: "tint", label: "Tint", help: "Corrects a green or magenta colour cast.", track: "tint" }, vibrance: { key: "vibrance", label: "Vibrance", help: "Mainly strengthens colours that are currently muted.", track: "vibrance" }, saturation: { key: "saturation", label: "Saturation", help: "Changes the strength of all colours.", track: "saturation" }, hue: { key: "hue", label: "Hue", help: "Rotates all colours around the colour wheel.", track: "hue" },
};
const GUIDED: readonly Control[] = [
  { ...CONTROLS.brightness, label: "Brighter / darker", help: "Lightens or darkens the whole image." }, { ...CONTROLS.shadows, label: "Dark detail", help: "Reveals or deepens detail in darker areas." }, { ...CONTROLS.highlights, label: "Bright detail", help: "Recovers or strengthens detail in brighter areas." }, { ...CONTROLS.contrast, label: "Punch", help: "Increases or softens separation between dark and light." }, { ...CONTROLS.temperature, label: "Warmth", help: "Makes the image look cooler or warmer." }, { ...CONTROLS.vibrance, label: "Colour richness", help: "Strengthens muted colours more gently than Saturation." },
];
const LIGHT: readonly TuneImageControl[] = ["brightness", "contrast", "shadows", "midtones", "highlights", "blackPoint", "whitePoint"];
const COLOUR: readonly TuneImageControl[] = ["vibrance", "saturation", "hue"];
const BALANCE: readonly TuneImageControl[] = ["temperature", "tint"];
function storedPresentation(): TunePresentation { try { return localStorage.getItem("photo-star.tune-presentation") === "advanced" ? "advanced" : "guided"; } catch { return "guided"; } }
function useActions(props: Props) { const draft = useRef(props.operation); useEffect(() => { draft.current = props.operation; }, [props.operation]); const preview = (values: PhotoEditOperation["values"]) => { const next = { ...draft.current, values }; draft.current = next; props.onPreviewChange(next); return next; }; const reset = (keys: readonly TuneImageControl[]) => { preview({ ...draft.current.values, ...Object.fromEntries(keys.map((key) => [key, TUNE_IMAGE_DEFAULTS[key]])) }); props.onCommit(draft.current); }; return { commit: () => props.onCommit(draft.current), preview: (key: TuneImageControl, candidate: number) => preview({ ...draft.current.values, [key]: candidate }), reset }; }
function Reset(props: { readonly label: string; readonly disabled: boolean; readonly onClick: () => void; }) { return <IconButton aria-label={`Reset ${props.label}`} className="p-1" disabled={props.disabled} title={`Reset ${props.label}`} type="button" onClick={props.onClick}><RotateCcw aria-hidden="true" size={13} /></IconButton>; }
function guidedControl(key: TuneImageControl): GuidedTuneImageControl | null { return TUNE_GUIDED_CONTROLS.find((candidate) => candidate === key) ?? null; }
function sliderRange(key: TuneImageControl, guidedKey: GuidedTuneImageControl | null, guided: boolean | undefined): readonly [number, number] {
  if (guided && guidedKey) { return TUNE_CONTROL_RANGES[guidedKey]; }
  if (key === "hue") { return [-180, 180]; }
  return [-100, 100];
}
function Slider(props: { readonly control: Control; readonly guided?: boolean; readonly operation: PhotoEditOperation; readonly onPreview: (key: TuneImageControl, value: number) => void; readonly onCommit: () => void; readonly onReset: () => void; readonly onFocus: (key: TuneImageControl | null) => void; }) {
  const current = tuneValue(props.operation.values, props.control.key); const key = props.control.key; const guidedKey = guidedControl(key); const [minimum, maximum] = sliderRange(key, guidedKey, props.guided);
  if (props.guided && guidedKey && isOutsideGuidedRange(guidedKey, current)) { return <div className="photo-tune-outside"><span>Advanced value: {formatTuneValue(key, current)}</span><Reset label={props.control.label} disabled={false} onClick={props.onReset} /><Button variant="secondary" onClick={() => document.getElementById("photo-tune-advanced")?.click()}>Open Advanced</Button></div>; }
  const style: RangeStyle = { "--tune-position": `${(current - minimum) / (maximum - minimum) * 100}%` };
  return <div className="space-y-1"><div className="flex items-center justify-between text-xs text-content-secondary"><label htmlFor={`${props.operation.id}-${key}`}>{props.control.label}</label><span className="flex items-center gap-1"><output className="font-mono tabular-nums text-content" htmlFor={`${props.operation.id}-${key}`}>{formatTuneValue(key, current)}</output><button aria-label={`Help: ${props.control.label}`} className="photo-tune-help" title={props.control.help} type="button">?</button><Reset label={props.control.label} disabled={current === 0} onClick={props.onReset} /></span></div><input id={`${props.operation.id}-${key}`} aria-describedby={`${props.operation.id}-${key}-help`} aria-valuetext={`${props.control.label}: ${formatTuneValue(key, current)}`} className={`photo-tune-range photo-tune-${props.control.track} w-full`} max={maximum} min={minimum} step="1" style={style} type="range" value={current} onBlur={props.onCommit} onChange={() => undefined} onFocus={() => props.onFocus(key)} onInput={(event) => props.onPreview(key, Number(event.currentTarget.value))} onKeyUp={props.onCommit} onPointerCancel={props.onCommit} onPointerUp={props.onCommit} onMouseLeave={() => props.onFocus(null)} /><span className="sr-only" id={`${props.operation.id}-${key}-help`}>{props.control.help}</span></div>;
}
function Group(props: { readonly title: string; readonly controls: readonly TuneImageControl[]; readonly operation: PhotoEditOperation; readonly actions: ReturnType<typeof useActions>; readonly active: TuneImageControl | null; readonly setActive: (key: TuneImageControl | null) => void; }) { return <details open><summary className="text-xs font-semibold text-content">{props.title}</summary><div className="mt-3 space-y-3">{props.controls.map((key) => <Slider key={key} control={CONTROLS[key]} operation={props.operation} onCommit={props.actions.commit} onFocus={props.setActive} onPreview={props.actions.preview} onReset={() => props.actions.reset([key])} />)}</div></details>; }
export function PhotoTuneOptions(props: Props) { const [presentation, setPresentation] = useState<TunePresentation>(storedPresentation); const [active, setActive] = useState<TuneImageControl | null>(null); const actions = useActions(props); const choose = (next: TunePresentation) => { setPresentation(next); try { localStorage.setItem("photo-star.tune-presentation", next); } catch { /* preference remains session-only */ } }; return <div className="space-y-4"><div aria-label="Tune image presentation" className="photo-tune-mode" role="group"><Button aria-pressed={presentation === "guided"} variant={presentation === "guided" ? "primary" : "secondary"} onClick={() => choose("guided")}>Guided</Button><Button aria-pressed={presentation === "advanced"} id="photo-tune-advanced" variant={presentation === "advanced" ? "primary" : "secondary"} onClick={() => choose("advanced")}>Advanced</Button></div>{presentation === "guided" ? <><fieldset className="space-y-3"><legend className="text-xs font-semibold text-content">Light</legend>{GUIDED.slice(0, 4).map((control) => <Slider key={control.key} control={control} guided operation={props.operation} onCommit={actions.commit} onFocus={setActive} onPreview={actions.preview} onReset={() => actions.reset([control.key])} />)}<Button variant="secondary" onClick={() => actions.reset(LIGHT)}>Reset Light</Button></fieldset><fieldset className="space-y-3"><legend className="text-xs font-semibold text-content">Colour</legend>{GUIDED.slice(4).map((control) => <Slider key={control.key} control={control} guided operation={props.operation} onCommit={actions.commit} onFocus={setActive} onPreview={actions.preview} onReset={() => actions.reset([control.key])} />)}<Button variant="secondary" onClick={() => actions.reset(["temperature", "vibrance"])}>Reset Colour</Button></fieldset></> : <><div aria-label={`Tonal regions: ${active ?? "none selected"}`} className={`photo-tune-tones photo-tune-tones-${active ?? "neutral"}`} role="img"><span>black</span><span>white</span></div><Group active={active} setActive={setActive} title="Light" controls={LIGHT} operation={props.operation} actions={actions} /><Group active={active} setActive={setActive} title="White balance" controls={BALANCE} operation={props.operation} actions={actions} /><Group active={active} setActive={setActive} title="Colour" controls={COLOUR} operation={props.operation} actions={actions} /></>}<Button variant="secondary" onClick={() => actions.reset(TUNE_IMAGE_CONTROLS)}>Reset all</Button></div>; }
