import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('gallery exposes a global timeline rail with release-to-seek wiring and stable tile selection keys', () => {
    const libraryViewSource = fs.readFileSync('src/ui/components/LibraryView.tsx', 'utf8');
    const toolbarSource = fs.readFileSync('src/ui/components/library/LibraryToolbar.tsx', 'utf8');
    const timelineRailSource = fs.readFileSync('src/ui/components/library/LibraryTimelineRail.tsx', 'utf8');
    const timelineHelpersSource = fs.readFileSync('src/ui/components/library/libraryViewTimeline.tsx', 'utf8');
    const appMainContentSource = fs.readFileSync('src/ui/components/app/AppMainContent.tsx', 'utf8');
    const loadedAppShellSource = fs.readFileSync('src/ui/components/app/LoadedAppShell.tsx', 'utf8');
    const layoutEngineSource = fs.readFileSync('src/ui/components/layout/LayoutEngine.tsx', 'utf8');
    const coreActionsSource = fs.readFileSync('src/ui/hooks/usePhotoLibrary.coreActions.ts', 'utf8');
    const photoLibrarySource = fs.readFileSync('src/ui/hooks/usePhotoLibrary.ts', 'utf8');
    const connectionMessagesSource = fs.readFileSync('src/boundary/runtime/usePhotoLibrary.connection.messages.ts', 'utf8');

    assert.match(libraryViewSource, /stats: LibraryStats \| null;/);
    assert.match(libraryViewSource, /galleryTimelineSeek: GalleryTimelineSeek \| null;/);
    assert.match(libraryViewSource, /isSeekingTimeline: boolean;/);
    assert.match(libraryViewSource, /onGalleryTimelineSeek: \(seek: GalleryTimelineSeek \| null\) => void;/);
    assert.doesNotMatch(toolbarSource, /LibraryTimelineRail/);
    assert.match(libraryViewSource, /timelineRail,/);
    assert.match(timelineHelpersSource, /<LibraryTimelineRail/);
    assert.match(libraryViewSource, /viewportBucketIndex/);
    assert.match(libraryViewSource, /topVisibleSelectionKey/);
    assert.match(libraryViewSource, /setTopVisibleSelectionKey/);
    assert.match(timelineHelpersSource, /visibleSelectionKey: string \| null;/);
    assert.doesNotMatch(timelineHelpersSource, /querySelectorAll<HTMLElement>\('\[data-selection-key\]'\)/);
    assert.match(timelineHelpersSource, /updateViewportBucketIndex\(params\.visibleSelectionKey\)/);
    assert.match(timelineRailSource, /type="range"/);
    assert.match(timelineRailSource, /writingMode: 'vertical-lr'/);
    assert.match(timelineRailSource, /transform: 'rotate\(180deg\)'/);
    assert.match(timelineRailSource, /gridTemplateRows/);
    assert.match(timelineRailSource, /getNewestFirstBuckets/);
    assert.doesNotMatch(timelineRailSource, /Oldest /);
    assert.doesNotMatch(timelineRailSource, /Newest /);
    assert.match(timelineRailSource, /Unknown date/);
    assert.match(timelineRailSource, /onMouseUp|onPointerUp|onKeyUp/);
    assert.match(appMainContentSource, /stats=\{props\.stats\}/);
    assert.match(appMainContentSource, /galleryTimelineSeek=\{props\.galleryTimelineSeek\}/);
    assert.match(appMainContentSource, /isSeekingTimeline=\{props\.isSeekingTimeline\}/);
    assert.match(loadedAppShellSource, /stats,/);
    assert.match(loadedAppShellSource, /galleryTimelineSeek,/);
    assert.match(loadedAppShellSource, /isSeekingTimeline,/);
    assert.match(loadedAppShellSource, /onGalleryTimelineSeek=\{actions\.seekGalleryTimeline\}/);
    assert.match(coreActionsSource, /setIsSeekingTimeline\(true\)/);
    assert.doesNotMatch(coreActionsSource, /seekGalleryTimeline[\s\S]*setAssets\(\[\]\)/);
    assert.match(photoLibrarySource, /setIsSeekingTimeline: state\.setIsSeekingTimeline/);
    assert.match(connectionMessagesSource, /params\.setIsSeekingTimeline\(false\)/);
    assert.match(layoutEngineSource, /data-selection-key=\{layoutItem\.item\.selectionKey\}/);
});
