import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('gallery exposes a global timeline rail with decade jump buttons and stable tile selection keys', () => {
    const libraryViewSource = fs.readFileSync('src/ui/components/LibraryView.tsx', 'utf8');
    const toolbarSource = fs.readFileSync('src/ui/components/library/LibraryToolbar.tsx', 'utf8');
    const timelineRailSource = fs.readFileSync('src/ui/components/library/LibraryTimelineRail.tsx', 'utf8');
    const timelineHelpersSource = fs.readFileSync('src/ui/components/library/libraryViewTimeline.tsx', 'utf8');
    const timelineModelSource = fs.readFileSync('src/ui/components/library/libraryTimelineModel.ts', 'utf8');
    const timelinePresentationSource = fs.readFileSync('src/ui/components/library/libraryViewPresentation.tsx', 'utf8');
    const timelineScrollResetSource = fs.readFileSync('src/ui/components/library/libraryTimelineSeekScrollReset.ts', 'utf8');
    const timelineJumpSource = fs.readFileSync('src/ui/components/library/libraryTimelineJump.ts', 'utf8');
    const visibleSelectionSource = fs.readFileSync('src/ui/components/library/libraryVisibleSelectionKey.ts', 'utf8');
    const appMainContentSource = fs.readFileSync('src/ui/components/app/AppMainContent.tsx', 'utf8');
    const loadedAppShellSource = fs.readFileSync('src/ui/components/app/LoadedAppShell.tsx', 'utf8');
    const layoutEngineSource = fs.readFileSync('src/ui/components/layout/LayoutEngine.tsx', 'utf8');
    const justifiedLayoutSource = fs.readFileSync('src/ui/components/layout/JustifiedLayout.tsx', 'utf8');
    const coreActionsSource = fs.readFileSync('src/ui/hooks/usePhotoLibrary.coreActions.ts', 'utf8');
    const photoLibrarySource = fs.readFileSync('src/ui/hooks/usePhotoLibrary.ts', 'utf8');
    const connectionMessagesSource = fs.readFileSync('src/boundary/runtime/usePhotoLibrary.connection.messages.ts', 'utf8');

    assert.match(libraryViewSource, /stats: LibraryStats \| null;/);
    assert.match(libraryViewSource, /galleryTimelineSeek: GalleryTimelineSeek \| null;/);
    assert.match(libraryViewSource, /isSeekingTimeline: boolean;/);
    assert.match(libraryViewSource, /onGalleryTimelineSeek: \(seek: GalleryTimelineSeek \| null\) => void;/);
    assert.doesNotMatch(toolbarSource, /LibraryTimelineRail/);
    assert.match(libraryViewSource, /timelineRail,/);
    assert.match(timelineHelpersSource, /<LibraryTimelineRail/);
    assert.match(timelineModelSource, /getTimelineSummaryForGalleryMode/);
    assert.match(timelinePresentationSource, /getTimelineSummaryForGalleryMode/);
    assert.match(timelinePresentationSource, /stats: LibraryStats \| null;/);
    assert.match(timelinePresentationSource, /viewportBucketIndex/);
    assert.match(libraryViewSource, /setTopVisibleSelectionKey/);
    assert.match(libraryViewSource, /useLibraryPresentationModel/);
    assert.match(libraryViewSource, /useLibraryTimelineJump/);
    assert.match(libraryViewSource, /handleTimelineJump,/);
    assert.match(fs.readFileSync('src/ui/components/library/libraryViewTimelineSync.ts', 'utf8'), /syncViewportBucketIndexFromScrollContainer/);
    assert.match(fs.readFileSync('src/ui/components/library/libraryViewTimelineSync.ts', 'utf8'), /syncViewportBucketIndexFromScrollContainer\(event\.currentTarget\)/);
    assert.match(fs.readFileSync('src/ui/components/library/libraryViewTimelineSync.ts', 'utf8'), /setTopVisibleSelectionKey\(getTopVisibleSelectionKeyFromScrollContainer\(event\.currentTarget\)\)/);
    assert.match(libraryViewSource, /useTimelineSeekScrollReset\(scrollRef, props\.galleryTimelineSeek, props\.isSeekingTimeline\)/);
    assert.match(timelineScrollResetSource, /scrollRef\.current\?\.scrollTo\(\{ top: 0, behavior: 'auto' \}\)/);
    assert.match(visibleSelectionSource, /querySelectorAll<HTMLElement>\('\[data-selection-key\]'\)/);
    assert.match(timelineHelpersSource, /visibleSelectionKey: string \| null;/);
    assert.doesNotMatch(timelineHelpersSource, /querySelectorAll<HTMLElement>\('\[data-selection-key\]'\)/);
    assert.match(timelineHelpersSource, /const viewportBucketIndex = findViewportTimelineBucketIndex\(params\.visibleSelectionKey, fallbackSelectionKey, selectionKeyToBucketIndex\);/);
    assert.doesNotMatch(timelineRailSource, /type="range"/);
    assert.match(timelineRailSource, /TimelineRailBucketButton/);
    assert.match(timelineRailSource, /onClick=\{\(\) =>/);
    assert.doesNotMatch(timelineRailSource, /setPointerCapture/);
    assert.doesNotMatch(timelineRailSource, /onPointerDown/);
    assert.doesNotMatch(timelineRailSource, /onPointerMove/);
    assert.doesNotMatch(timelineRailSource, /onPointerUp/);
    assert.doesNotMatch(timelineRailSource, /setInterval|window\.setInterval/);
    assert.doesNotMatch(timelineRailSource, /data-timeline-rail-track/);
    assert.doesNotMatch(timelineRailSource, /getTimelineRailBucketIndexFromPointer/);
    assert.doesNotMatch(timelineRailSource, /key=.*vp=.*shown=/);
    assert.doesNotMatch(timelineRailSource, /Oldest /);
    assert.doesNotMatch(timelineRailSource, /Newest /);
    assert.match(timelineRailSource, /Unknown date/);
    assert.match(appMainContentSource, /stats=\{props\.stats\}/);
    assert.match(appMainContentSource, /galleryTimelineSeek=\{props\.galleryTimelineSeek\}/);
    assert.match(appMainContentSource, /isSeekingTimeline=\{props\.isSeekingTimeline\}/);
    assert.match(loadedAppShellSource, /stats,/);
    assert.match(loadedAppShellSource, /galleryTimelineSeek,/);
    assert.match(loadedAppShellSource, /isSeekingTimeline,/);
    assert.match(loadedAppShellSource, /onGalleryTimelineSeek=\{actions\.seekGalleryTimeline\}/);
    assert.match(coreActionsSource, /setIsSeekingTimeline\(true\)/);
    assert.doesNotMatch(coreActionsSource, /seekGalleryTimeline[\s\S]*setAssets\(\[\]\)/);
    assert.match(photoLibrarySource, /setIsSeekingTimeline: state\.setIsSeekingTimeline/);
    assert.match(connectionMessagesSource, /params\.setIsSeekingTimeline\(false\)/);
    assert.match(connectionMessagesSource, /else if \(isPreservedPagingAssetRefreshId\(msg\.id\)\)/);
    assert.match(connectionMessagesSource, /return assets;/);
    assert.match(layoutEngineSource, /data-selection-key=\{layoutItem\.item\.selectionKey\}/);
    assert.match(justifiedLayoutSource, /data-time-section-id=\{sectionId\}/);
    assert.match(timelineJumpSource, /getTimelineSectionIdForSeek/);
    assert.match(timelineJumpSource, /loadedSectionIdsRef/);
    assert.match(timelineJumpSource, /timelineJumpRequest/);
    assert.match(timelineJumpSource, /onGalleryTimelineSeek\(seek\)/);
});
