import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('photo editor is registered across command, overlay, and gallery priority boundaries', () => {
    const handlers = readFileSync('src/services/handlers.ts', 'utf8');
    const appOverlays = readFileSync('src/ui/components/app/AppOverlays.tsx', 'utf8');
    const singlePhoto = readFileSync('src/ui/components/SinglePhotoView.tsx', 'utf8');
    const actionMenu = readFileSync('src/ui/components/single-photo/ActionOverlayControls.tsx', 'utf8');
    const editor = readFileSync('src/ui/components/photo-editor/PhotoEditorWorkspace.tsx', 'utf8');
    const editorPreview = readFileSync('src/ui/components/photo-editor/PhotoEditorPreview.tsx', 'utf8');
    const editorSidebar = readFileSync('src/ui/components/photo-editor/PhotoEditorSidebar.tsx', 'utf8');
    const editorTools = readFileSync('src/ui/components/photo-editor/photoEditorTools.ts', 'utf8');
    const beforeChangeButton = readFileSync('src/ui/components/photo-editor/PhotoBeforeChangeButton.tsx', 'utf8');
    const maskCandidates = readFileSync('src/ui/components/photo-editor/maskCandidates.ts', 'utf8');
    const maskOverlay = readFileSync('src/ui/components/photo-editor/PhotoMaskOverlay.tsx', 'utf8');
    const maskPanel = readFileSync('src/ui/components/photo-editor/PhotoMaskPanel.tsx', 'utf8');
    const toolBoundary = readFileSync('src/ui/components/photo-editor/PhotoEditorToolBoundary.tsx', 'utf8');
    const cropOverlay = readFileSync('src/ui/components/photo-editor/PhotoCropOverlay.tsx', 'utf8');
    const cropOptions = readFileSync('src/ui/components/photo-editor/PhotoCropOptions.tsx', 'utf8');
    const rotateOverlay = readFileSync('src/ui/components/photo-editor/PhotoRotateOverlay.tsx', 'utf8');
    const rotateOptions = readFileSync('src/ui/components/photo-editor/PhotoRotateOptions.tsx', 'utf8');
    const colourPopOptions = readFileSync('src/ui/components/photo-editor/PhotoColourPopOptions.tsx', 'utf8');
    const colourPopOverlay = readFileSync('src/ui/components/photo-editor/PhotoColourPopOverlay.tsx', 'utf8');
    const effectsOptions = readFileSync('src/ui/components/photo-editor/PhotoEffectsOptions.tsx', 'utf8');
    const effectsOverlay = readFileSync('src/ui/components/photo-editor/PhotoEffectsOverlay.tsx', 'utf8');
    const effectsRenderer = readFileSync('src/shared/photoEditing/effects.ts', 'utf8');
    const focusOptions = readFileSync('src/ui/components/photo-editor/PhotoFocusOptions.tsx', 'utf8');
    const focusOverlay = readFileSync('src/ui/components/photo-editor/PhotoFocusOverlay.tsx', 'utf8');
    const focusRenderer = readFileSync('src/shared/photoEditing/focus.ts', 'utf8');
    const automaticPanel = readFileSync('src/ui/components/photo-editor/PhotoAutomaticPanel.tsx', 'utf8');
    const automaticAnalysis = readFileSync('src/shared/photoEditing/automatic.ts', 'utf8');
    const tuneOptions = readFileSync('src/ui/components/photo-editor/PhotoTuneOptions.tsx', 'utf8');
    const tuneRenderer = readFileSync('src/shared/photoEditing/tune.ts', 'utf8');
    const previewQueue = readFileSync('src/ui/components/photo-editor/photoEditPreviewQueue.ts', 'utf8');
    const singlePhotoOverlay = readFileSync('src/ui/components/single-photo/SinglePhotoOverlay.tsx', 'utf8');
    const grouping = readFileSync('src/services/handlers/assetGroupingQueryFragments.ts', 'utf8');
    const editorPreviewStrings = editorPreview.replaceAll('"', "'");
    const editorSidebarStrings = editorSidebar.replaceAll('"', "'");
    const editorToolStrings = editorTools.replaceAll('"', "'");
    const cropOptionStrings = cropOptions.replaceAll('"', "'");
    assert.match(handlers, /photoEditCommandHandlers/);
    assert.match(appOverlays, /preview_photo_edit/);
    assert.match(singlePhoto, /PhotoEditorWorkspace/);
    assert.match(actionMenu, /label="Edit photo"/);
    assert.match(editorToolStrings, /id: 'dehaze'[\s\S]*label: 'Dehaze'/);
    assert.match(editorToolStrings, /id: 'colour_pop'[\s\S]*label: 'Colour pop'/);
    assert.match(editorToolStrings, /id: 'effects'[\s\S]*label: 'Effects'/);
    assert.match(editorToolStrings, /id: 'focus'[\s\S]*label: 'Focus'/);
    assert.match(editorTools, /defaults: \{ colourCount: 0, colourRange: 28, softness: 0\.35 \}/);
    assert.match(editorSidebarStrings, /operation\.tool === 'colour_pop'/);
    assert.match(editorSidebar, /PhotoColourPopOptions/);
    assert.match(editorPreview, /PhotoColourPopOverlay/);
    assert.match(editorSidebar, /PhotoEffectsOptions/);
    assert.match(editorPreview, /PhotoEffectsOverlay/);
    assert.match(effectsOptions, /Ripple/);
    assert.match(effectsOptions, /Sunburst/);
    assert.match(effectsOptions, /Lens flare/);
    assert.match(effectsOptions, /Light leak/);
    assert.match(effectsOverlay, /Click to place the effect centre/);
    assert.match(effectsRenderer, /applyRipple/);
    assert.match(effectsRenderer, /applySunburst/);
    assert.match(editorSidebar, /PhotoFocusOptions/);
    assert.match(editorPreview, /PhotoFocusOverlay/);
    assert.match(focusOptions, /Tilt-shift/);
    assert.match(focusOptions, /Group focus/);
    assert.match(focusOptions, /Focus tunnel/);
    assert.match(focusOverlay, /Shift-click to add a point/);
    assert.match(focusRenderer, /applyFocusPixels/);
    assert.match(focusRenderer, /orbitalBlur/);
    assert.match(editorSidebar, /PhotoAutomaticPanel/);
    assert.match(editorSidebar, /AutomaticToolTile/);
    assert.match(editorSidebar, /Automatic settings/);
    assert.match(automaticPanel, /Apply \{selected\.length\}/);
    assert.match(automaticPanel, /data-feedback-mode|InlineFeedback/);
    assert.match(automaticPanel, /EXIF orientation is already corrected/);
    assert.match(automaticAnalysis, /estimateStraighten/);
    assert.match(automaticAnalysis, /pixelAttentionCrop/);
    assert.match(tuneOptions, /Auto tune/);
    assert.match(tuneOptions, /Auto light/);
    assert.match(tuneOptions, /Auto colour/);
    assert.match(tuneOptions, /Automatically set/);
    assert.match(tuneRenderer, /applyAdvancedTunePixels/);
    assert.match(editor, /const sourceOperation = history\.present\.operations\.find/);
    assert.match(editor, /const operationsBefore = history\.present\.operations\.slice/);
    assert.match(editor, /PhotoBeforeChangeButton/);
    assert.match(editor, /showWithoutChange=\{showWithoutChange\}/);
    assert.match(beforeChangeButton, /Show without change/);
    assert.match(beforeChangeButton, /Eye/);
    assert.match(beforeChangeButton, /Undo2/);
    assert.match(beforeChangeButton, /setPointerCapture/);
    assert.match(beforeChangeButton, /onPointerDown=\{pointerDown\}/);
    assert.match(beforeChangeButton, /onPointerUp=\{pointerUp\}/);
    assert.match(beforeChangeButton, /onPointerCancel=\{pointerUp\}/);
    assert.match(beforeChangeButton, /onLostPointerCapture=\{release\}/);
    assert.match(beforeChangeButton, /onKeyDown=\{keyDown\}/);
    assert.match(beforeChangeButton, /onKeyUp=\{keyUp\}/);
    assert.match(beforeChangeButton, /aria-pressed=\{props\.pressed\}/);
    assert.match(colourPopOptions, /quantizeColourPalette/);
    assert.match(colourPopOptions, /Colours to keep/);
    assert.match(colourPopOptions, /Image palette/);
    assert.match(colourPopOptions, /Colour range/);
    assert.match(colourPopOverlay, /applyColourPopPixels/);
    assert.match(colourPopOverlay, /colourAt\((?:props\.)?source, point\)/);
    assert.match(colourPopOverlay, /Click a colour to keep it/);
    assert.match(editorSidebar, /grid grid-cols-3 gap-2/);
    assert.equal(editorTools.match(/icon: \w+,\s*defaults:/g)?.length, 11);
    assert.equal(cropOverlay.match(/Resize crop from/g)?.length, 1);
    assert.match(cropOverlay, /Move image within crop/);
    assert.match(cropOverlay, /CROP_SETTLE_DELAY_MS = 3000/);
    assert.match(cropOverlay, /data-crop-frame="true"/);
    assert.match(cropOverlay, /data-crop-handle=/);
    assert.match(cropOverlay, /bg-transparent p-0/);
    assert.match(cropOverlay, /onDraftChange\(draftRef\.current\)/);
    assert.match(cropOverlay, /data-crop-guide=/);
    assert.match(cropOptionStrings, /label: '19:6'/);
    assert.match(cropOptionStrings, /label: 'Thirds'/);
    assert.match(cropOptionStrings, /label: 'Golden'/);
    assert.match(cropOptionStrings, /label: 'Golden spiral'/);
    assert.match(cropOptionStrings, /label: 'Harmonious'/);
    assert.match(cropOptionStrings, /label: 'Radial'/);
    assert.match(cropOptionStrings, /label: 'Circular'/);
    assert.match(cropOptions, /preserveAspectRatio="none"/);
    assert.match(cropOptions, /label="Horizontal"/);
    assert.match(cropOptions, /label="Vertical"/);
    assert.match(editorPreview, /PhotoRotateOverlay/);
    assert.match(editorPreview, /PhotoMaskOverlay/);
    assert.match(editorSidebar, /PhotoMaskPanel/);
    assert.match(editorTools, /pivotX: 0\.5,[\s\S]*pivotY: 0\.5,[\s\S]*expandCanvas: true,[\s\S]*fillMode: 0/);
    assert.match(rotateOverlay, /Straighten from line/);
    assert.match(rotateOverlay, /const point = localPoint\(event\);/);
    assert.doesNotMatch(rotateOverlay, /setLine\(\(current\).*localPoint\(event\)/);
    assert.match(rotateOverlay, /Rotation centre; drag to move/);
    assert.match(rotateOverlay, /const displayedAngle = props\.showWithoutChange \? 0 : angle/);
    assert.match(rotateOverlay, /showControls=\{!props\.showWithoutChange\}/);
    assert.match(colourPopOverlay, /props\.showWithoutChange[\s\S]*\? (?:props\.)?source\.data/);
    assert.match(cropOverlay, /props\.showWithoutChange && props\.sourceUrl/);
    assert.match(rotateOptions, /label="Keep dimensions"/);
    assert.match(rotateOptions, /label="Expand canvas"/);
    assert.match(rotateOptions, /label="90° anticlockwise"/);
    assert.match(rotateOptions, /label="90° clockwise"/);
    assert.match(rotateOptions, /label="Flip horizontal"/);
    assert.match(rotateOptions, /label="Flip vertical"/);
    assert.match(rotateOptions, /ANGLE_MARKERS = \[-90, -45, -30, 0, 30, 45, 90\]/);
    assert.match(rotateOptions, /Hold Shift for 5° steps/);
    assert.match(rotateOptions, /label="AI fill"/);
    assert.match(rotateOptions, /disabled icon=\{Sparkles\}/);
    assert.match(editorPreview, /region="preview"/);
    assert.match(editorSidebar, /region="controls"/);
    assert.match(editorPreview, /function ToolPreviewRegion/);
    assert.match(editorSidebar, /function ToolControlsRegion/);
    assert.match(editorSidebar, /function AccordionSection/);
    assert.match(editorSidebar, /aria-expanded=\{props\.open\}/);
    assert.match(editorSidebarStrings, /primaryPanel === 'tools'/);
    assert.match(editorSidebarStrings, /primaryPanel === 'settings'/);
    assert.match(editorSidebarStrings, /function settingsTitle\(automaticActive: boolean, selected: PhotoEditOperation \| null\)[\s\S]*'Automatic settings'[\s\S]*`\$\{selected\.name\} settings`[\s\S]*'Tool settings'/);
    assert.match(automaticPanel, /new Set\(props\.suggestions\.map\(\(suggestion\) => suggestion\.id\)\)/);
    assert.doesNotMatch(automaticPanel, /High confidence|Good confidence|Optional|confidenceLabel/);
    assert.match(automaticPanel, /Each selected correction appears in Layers & changes/);
    assert.doesNotMatch(editorSidebar, /return <Card><PhotoCropOptions/);
    assert.doesNotMatch(editorSidebar, /<h3 className="font-semibold text-content">\{definition\.label\}<\/h3>/);
    assert.match(maskPanel, /className="divide-y divide-content\/10"/);
    assert.match(editorSidebar, /border-l-2 py-2 pl-2 transition-colors/);
    assert.match(maskPanel, /props\.masks\.length > 0/);
    assert.doesNotMatch(cropOptions, />Crop<\/h3>/);
    assert.match(editorPreviewStrings, /key=\{`\$\{props\.selected\?\.id \?\? 'none'\}-preview`\}/);
    assert.match(editorSidebarStrings, /key=\{`\$\{props\.selected\.id\}-controls`\}/);
    assert.match(toolBoundary, /Your edit stack is still available\./);
    assert.match(toolBoundary, /Try this tool again/);
    assert.doesNotMatch(toolBoundary, /onClose|Return to photo/);
    assert.match(previewQueue, /this\.pending = \{ input, revision \}/);
    assert.doesNotMatch(singlePhotoOverlay, /fixed right-4 top-4/);
    assert.match(grouping, /WHEN 'edit_version' THEN 0/);
    assert.match(maskCandidates, /asset\.frame_detection/);
    assert.match(maskCandidates, /projection\[field\]/);
    assert.match(maskCandidates, /asset\.faces/);
    assert.match(maskOverlay, /data-mask-canvas/);
    assert.match(maskOverlay, /DrawingOverlay/);
});
