export const PHOTO_METADATA_ASSERTION_FIELD_PATHS = [
    'caption',
    'description',
    'location',
    'estimated_date.display_label',
    'estimated_date.most_likely_date',
    'estimated_date.min_date',
    'estimated_date.max_date',
    'estimated_date.rationale',
    'keywords',
    'emotional_impact',
    'quality.technical',
    'quality.lighting',
    'quality.composition',
    'quality.emotional',
    'quality.discard',
    'authenticity.score',
    'authenticity.reasons',
    'subjects[*].label',
    'subjects[*].location_desc',
    'subjects[*].gender',
    'subjects[*].animal_type',
    'subjects[*].age_range',
    'subjects[*].dob_range',
    'subjects[*].emotion',
    'subjects[*].gaze',
    'subjects[*].features',
    'subjects[*].uniform',
    'subjects[*].suggested_names',
    'regions_of_interest[*].label',
    'regions_of_interest[*].kind',
    'regions_of_interest[*].significance',
] as const;

export type PhotoMetadataAssertionFieldPath = typeof PHOTO_METADATA_ASSERTION_FIELD_PATHS[number];
