import type { WorkflowDefinition } from '../contracts';

export const simulationWorkflowDefinition: WorkflowDefinition = {
    id: 'runtime.simulation_workflow',
    version: 1,
    inputs: ['folder'],
    presentation: {
        defaultRunLabel: 'Simulation Workflow',
        milestones: [
            { id: 'enumeration', label: 'Simulating Discovery' },
            { id: 'fast_processing', label: 'Fast Processing' },
            { id: 'medium_processing', label: 'Medium Processing' },
            { id: 'slow_processing', label: 'Slow Processing' },
        ],
        stages: [
            {
                id: 'enumeration',
                label: 'Discovery',
                description: 'Simulate discovery of items.',
                nodeIds: ['enumerate-sim'],
            },
            {
                id: 'fast_processing',
                label: 'Fast Processing',
                description: 'Simulate fast task step.',
                nodeIds: ['fast-task-sim', 'fast-task-sim-2', 'fast-task-sim-3'],
            },
            {
                id: 'medium_processing',
                label: 'Medium Processing',
                description: 'Simulate medium task step.',
                nodeIds: [
                    'medium-task-sim',
                    'medium-branch-success-each',
                    'medium-branch-failure-each',
                    'medium-branch-1-step-1',
                    'medium-branch-1-step-2',
                    'medium-branch-1-step-3',
                    'medium-branch-2-step-1',
                    'medium-branch-3-step-1',
                ],
            },
            {
                id: 'slow_processing',
                label: 'Slow Processing',
                description: 'Simulate slow task step.',
                nodeIds: ['slow-task-sim'],
            },
        ],
    },
    nodes: [
        {
            id: 'enumerate-sim',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'once_per_batch',
            completesMilestones: ['enumeration'],
            outputsTo: ['fast-task-sim'],
            parameters: { mode: 'enumerator' },
            presentation: {
                label: 'Mock Discovery',
                countNoun: { singular: 'item', plural: 'items' },
            },
        },
        {
            id: 'fast-task-sim',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['fast-task-sim-2'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: {
                label: 'Fast Node 1',
                artifactNoun: { singular: 'result', plural: 'results' },
            },
        },
        {
            id: 'fast-task-sim-2',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['fast-task-sim-3'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: {
                label: 'Fast Node 2',
                artifactNoun: { singular: 'result', plural: 'results' },
            },
        },
        {
            id: 'fast-task-sim-3',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            completesMilestones: ['fast_processing'],
            outputsTo: ['medium-task-sim'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: {
                label: 'Fast Node 3',
                artifactNoun: { singular: 'result', plural: 'results' },
            },
        },
        {
            id: 'medium-task-sim',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['medium-branch-success-each'],
            onFailureTo: ['medium-branch-failure-each'],
            parameters: { mode: 'task', speed: 'medium', errorRate: 5, errorType: 'asset' },
            presentation: {
                label: 'Medium Step (5% error)',
                artifactNoun: { singular: 'result', plural: 'results' },
            },
        },
        {
            id: 'medium-branch-success-each',
            kind: 'control',
            controlType: 'for_each',
            outputsTo: ['medium-branch-1-step-1', 'medium-branch-2-step-1'],
            presentation: { label: 'Branch Successful Items' },
        },
        {
            id: 'medium-branch-failure-each',
            kind: 'control',
            controlType: 'for_each',
            outputsTo: ['medium-branch-3-step-1'],
            presentation: { label: 'Branch Failed Items' },
        },
        {
            id: 'medium-branch-1-step-1',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['medium-branch-1-step-2'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: { label: 'Branch 1: Step 1' },
        },
        {
            id: 'medium-branch-1-step-2',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['medium-branch-1-step-3'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: { label: 'Branch 1: Step 2' },
        },
        {
            id: 'medium-branch-1-step-3',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['slow-task-sim'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: { label: 'Branch 1: Step 3' },
        },
        {
            id: 'medium-branch-2-step-1',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            outputsTo: ['slow-task-sim'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: { label: 'Branch 2: Step 1' },
        },
        {
            id: 'medium-branch-3-step-1',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            completesMilestones: ['medium_processing'],
            parameters: { mode: 'task', speed: 'fast', errorRate: 0 },
            presentation: { label: 'Error Cleanup Step' },
        },
        {
            id: 'slow-task-sim',
            kind: 'module',
            moduleId: 'runtime.simulator',
            runMode: 'per_subject',
            completesMilestones: ['slow_processing'],
            presentation: {
                label: 'Slow AI Step',
                artifactNoun: { singular: 'metadata', plural: 'metadata' },
            },
        },
    ],
    parameters: [
        { id: 'mode', valueType: 'string', required: true },
        { id: 'iterations', valueType: 'string', required: false },
        { id: 'speed', valueType: 'string', required: false },
        { id: 'errorType', valueType: 'string', required: false },
        { id: 'errorRate', valueType: 'string', required: false },
        { id: 'mockPayloadTemplate', valueType: 'string', required: false },
        { id: 'resourceLoadMode', valueType: 'string', required: false },
    ],
};
