import sharp from 'sharp';
import type { PhotoEditMask, PhotoEditOperation } from '../../boundary/contracts/photoEditor';
import { PhotoEditToolRegistry } from './photoEditToolRegistry.ts';
import type { PhotoEditToolRenderPipeline } from './photoEditToolPlugin.ts';

type RenderOptions = { maxWidth?: number };
function clamp(value: number, minimum: number, maximum: number): number { return Math.min(maximum, Math.max(minimum, value)); }
async function applyOperation(input: Buffer, operation: PhotoEditOperation): Promise<Buffer> { const plugin = (await getPhotoEditToolRegistry()).get(operation.tool); if (plugin?.renderExact) { plugin.validateOperation?.(operation); return plugin.renderExact(input, operation, (value) => sharp(value) as unknown as PhotoEditToolRenderPipeline); } return input; }
let photoEditToolRegistry: PhotoEditToolRegistry | undefined;
async function getPhotoEditToolRegistry(): Promise<PhotoEditToolRegistry> { if (!photoEditToolRegistry) { photoEditToolRegistry = new PhotoEditToolRegistry(); const { generatedPhotoEditToolPlugins } = await import('./generatedPhotoEditToolPluginRegistry.ts'); for (const plugin of generatedPhotoEditToolPlugins) { photoEditToolRegistry.registerPlugin(plugin); } } return photoEditToolRegistry; }
function shapeMarkup(mask: PhotoEditMask, width: number, height: number, fill: string): string { const box = mask.box ?? { x: 0.2, y: 0.15, width: 0.6, height: 0.7 }; if (mask.kind === 'polygon' && mask.points && mask.points.length >= 3) { return `<polygon points="${mask.points.map((point) => `${point.x * width},${point.y * height}`).join(' ')}" fill="${fill}"/>`; } const x = box.x * width; const y = box.y * height; const boxWidth = box.width * width; const boxHeight = box.height * height; return mask.kind === 'ellipse' || mask.kind === 'subject' ? `<ellipse cx="${x + boxWidth / 2}" cy="${y + boxHeight / 2}" rx="${boxWidth / 2}" ry="${boxHeight / 2}" fill="${fill}"/>` : `<rect x="${x}" y="${y}" width="${boxWidth}" height="${boxHeight}" rx="2" fill="${fill}"/>`; }
function buildMaskSvg(mask: PhotoEditMask, width: number, height: number): Buffer { const isInverted = Boolean(mask.inverted) !== (mask.kind === 'background'); const blur = clamp(mask.feather, 0, 0.25) * Math.min(width, height); const filter = blur > 0 ? `<filter id="f"><feGaussianBlur stdDeviation="${blur}"/></filter>` : ''; const attribute = blur > 0 ? ' filter="url(#f)"' : ''; const shape = `<g${attribute}>${shapeMarkup(mask, width, height, 'white')}</g>`; const inverted = `<mask id="m"><rect width="100%" height="100%" fill="white"/><g${attribute}>${shapeMarkup(mask, width, height, 'black')}</g></mask><rect width="100%" height="100%" fill="white" mask="url(#m)"/>`; return Buffer.from(`<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg"><defs>${filter}</defs>${isInverted ? inverted : shape}</svg>`); }
async function applyMaskedOperation(input: Buffer, operation: PhotoEditOperation, mask: PhotoEditMask): Promise<Buffer> { const edited = await applyOperation(input, operation); const metadata = await sharp(input).metadata(); if (!metadata.width || !metadata.height) { return edited; } const masked = await sharp(edited).ensureAlpha().composite([{ input: buildMaskSvg(mask, metadata.width, metadata.height), blend: 'dest-in' }]).png().toBuffer(); return sharp(input).ensureAlpha().composite([{ input: masked, blend: 'over' }]).png().toBuffer(); }
export async function renderPhotoEdit(source: string | Buffer, operations: PhotoEditOperation[], masks: PhotoEditMask[], options: RenderOptions = {}): Promise<Buffer> { const sourcePipeline = sharp(source).rotate(); if (options.maxWidth) { sourcePipeline.resize(options.maxWidth, null, { fit: 'inside', withoutEnlargement: true }); } let current: Buffer = await sourcePipeline.png().toBuffer(); const masksById = new Map(masks.map((mask) => [mask.id, mask])); for (const operation of operations) { if (!operation.enabled) { continue; } const mask = operation.maskId ? masksById.get(operation.maskId) : undefined; const plugin = (await getPhotoEditToolRegistry()).get(operation.tool); current = mask && plugin?.capabilities?.maskCompatible ? await applyMaskedOperation(current, operation, mask) : await applyOperation(current, operation); } return current; }
