// This file is generated by tooling/scripts/repo/generate-photo-edit-tool-registry.mjs. Do not edit.
import type { PhotoEditToolPlugin } from './photoEditToolPlugin.ts';
import plugin0 from './tools/plugins/grayscale/manifest.ts';

export const generatedPhotoEditToolPlugins: readonly PhotoEditToolPlugin[] = [
    plugin0,
];
