import sharp from 'sharp';
import type { PhotoEditOperation } from '../../../../../boundary/contracts/photoEditor.ts';

type Placement = { height: number; left: number; top: number; width: number };
const FILL = { transparent: 0, black: 1, white: 2 } as const;
function clamp(value: number, minimum: number, maximum: number): number { return Math.min(maximum, Math.max(minimum, value)); }
function numberValue(operation: PhotoEditOperation, key: string, fallback: number): number { const value = operation.values[key]; return typeof value === 'number' && Number.isFinite(value) ? value : fallback; }
function booleanValue(operation: PhotoEditOperation, key: string, fallback: boolean): boolean { const value = operation.values[key]; return typeof value === 'boolean' ? value : fallback; }
function placement(params: { angle: number; expandCanvas: boolean; height: number; pivotX: number; pivotY: number; rotatedHeight: number; rotatedWidth: number; width: number }): Placement { const radians = params.angle * Math.PI / 180; const centreX = params.width / 2; const centreY = params.height / 2; const pivotX = params.pivotX * params.width; const pivotY = params.pivotY * params.height; const deltaX = centreX - pivotX; const deltaY = centreY - pivotY; const left = pivotX + deltaX * Math.cos(radians) - deltaY * Math.sin(radians) - params.rotatedWidth / 2; const top = pivotY + deltaX * Math.sin(radians) + deltaY * Math.cos(radians) - params.rotatedHeight / 2; if (!params.expandCanvas) { return { height: params.height, left: Math.round(left), top: Math.round(top), width: params.width }; } const minX = Math.min(0, left); const minY = Math.min(0, top); return { height: Math.ceil(Math.max(params.height, top + params.rotatedHeight) - minY), left: Math.round(left - minX), top: Math.round(top - minY), width: Math.ceil(Math.max(params.width, left + params.rotatedWidth) - minX) }; }
function background(operation: PhotoEditOperation): { alpha: number; b: number; g: number; r: number } { const fillMode = Math.round(numberValue(operation, 'fillMode', FILL.transparent)); if (fillMode === FILL.black) { return { r: 0, g: 0, b: 0, alpha: 1 }; } if (fillMode === FILL.white) { return { r: 255, g: 255, b: 255, alpha: 1 }; } return { r: 0, g: 0, b: 0, alpha: 0 }; }
async function clipped(params: { data: Buffer; destinationHeight: number; destinationWidth: number; height: number; left: number; top: number; width: number }): Promise<{ data: Buffer; left: number; top: number } | null> { const sourceLeft = Math.max(0, -params.left); const sourceTop = Math.max(0, -params.top); const left = Math.max(0, params.left); const top = Math.max(0, params.top); const width = Math.min(params.width - sourceLeft, params.destinationWidth - left); const height = Math.min(params.height - sourceTop, params.destinationHeight - top); if (width <= 0 || height <= 0) { return null; } if (sourceLeft === 0 && sourceTop === 0 && width === params.width && height === params.height) { return { data: params.data, left, top }; } return { data: await sharp(params.data).extract({ left: sourceLeft, top: sourceTop, width, height }).png().toBuffer(), left, top }; }
export async function renderRotate(input: Buffer, operation: PhotoEditOperation): Promise<Buffer> { const angle = numberValue(operation, 'angle', 0); const flipHorizontal = booleanValue(operation, 'flipHorizontal', false); const flipVertical = booleanValue(operation, 'flipVertical', false); if (Math.abs(angle % 360) < 0.000_001 && !flipHorizontal && !flipVertical) { return input; } const metadata = await sharp(input).metadata(); if (!metadata.width || !metadata.height) { return input; } let transform = sharp(input); if (flipVertical) { transform = transform.flip(); } if (flipHorizontal) { transform = transform.flop(); } const rotated = await transform.rotate(angle, { background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer({ resolveWithObject: true }); const frame = placement({ angle, expandCanvas: booleanValue(operation, 'expandCanvas', true), height: metadata.height, pivotX: clamp(numberValue(operation, 'pivotX', 0.5), 0, 1), pivotY: clamp(numberValue(operation, 'pivotY', 0.5), 0, 1), rotatedHeight: rotated.info.height, rotatedWidth: rotated.info.width, width: metadata.width }); const overlay = await clipped({ data: rotated.data, destinationHeight: frame.height, destinationWidth: frame.width, height: rotated.info.height, left: frame.left, top: frame.top, width: rotated.info.width }); const canvas = sharp({ create: { width: frame.width, height: frame.height, channels: 4, background: background(operation) } }); return overlay ? canvas.composite([{ input: overlay.data, left: overlay.left, top: overlay.top }]).png().toBuffer() : canvas.png().toBuffer(); }
