// This file is generated by tooling/scripts/repo/generate-semantic-predicate-registry.mjs. Do not edit.
import type { SemanticPredicatePlugin } from './contracts';
import plugin0 from './plugins/depicts/manifest';
import plugin1 from './plugins/derived-from/manifest';
import plugin2 from './plugins/represents-photograph/manifest';

export const generatedSemanticPredicatePlugins: readonly SemanticPredicatePlugin[] = [
    plugin0,
    plugin1,
    plugin2,
];
